site_name: vcat

repo_url: https://github.com/mpifr-vlbi/VCAT/

theme:
  name: readthedocs
  locale: en

extra_css:
  - css/extra.css

use_directory_urls: false

plugins:
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - admonition

nav:
  - VCAT Documention: index.md

  - Example Notebooks: 
    - Tutorial Overview: tutorials.md
    - Plotting Images: examples/ImageDataPlots.ipynb
    - Modifying Images: examples/ImageOperations.ipynb
    - Plotting ImageCubes: examples/ImageCubePlots.ipynb
    - Modifying ImageCubes: examples/ImageCubeOperations.ipynb
    - Alignment: examples/Alignment.ipynb
    - Model Component Analysis: examples/ModelComponents.ipynb
    - Ridgeline Fitting: examples/Ridgeline.ipynb
    - Stacking: examples/Stacking.ipynb
    - Turnover Frequency: examples/TurnoverFrequency.ipynb

  - Code Documentation: 
    - Code Overview: overview.md
    - ImageData: imagedata.md
    - ImageCube: imagecube.md
    - vcat.helpers: helpers.md

  - About:
    - License: license.md
    - Release Notes: release-note.md
