site_name: vcat

repo_url: https://github.com/mpifr-vlbi/VCAT/

theme:
  name: readthedocs

plugins:
  - mkdocstrings

nav:
  - VCAT Docs: index.md
  - User Guide: tutorials.md
  - References: 
    - References Overview: references.md
    - imageData: imagedata.md
    - imageCube: imagecube.md
  - About:
    - License: license.md
    - Release Notes: release-note.md
