#General settings:
difmap_path: "/usr/local/difmap/uvf_difmap_2.5g/"
uvw: [0,-1]

#Method selection
noise_method: "Histogram Fit"
mfit_err_method: "flat"
res_lim_method: "Kovalev05"

#Plot settings
font: "Quicksand"
plot_colors: ["#FED789FF", "#023743FF", "#72874EFF", "#476F84FF", "#A4BED5FF", "#453947FF"]
plot_markers: [".",".",".",".",".","."]

logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: ""
